name: ${project.name}
version: ${project.version}
main: Main
api-version: 1.18
authors: [ MineStar ]
commands:
  currency:
    aliases: [  ]
permissions:
  kr.kro.minestar.currency.default:
    description:
  kr.kro.minestar.currency.admin:
    description: